"""phase 3: execution, payment links, webhooks, concurrency

Revision ID: f3608d69ea91
Revises: 68a5f5373894
Create Date: 2026-08-30 11:25:53.449899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3608d69ea91'
down_revision: Union[str, None] = '68a5f5373894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_webhook_events',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_webhook_events_dedup_key'), 'processed_webhook_events', ['dedup_key'], unique=True)
    op.create_table('recovery_payment_requests',
    sa.Column('recovery_case_id', sa.Uuid(), nullable=False),
    sa.Column('recovery_attempt_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_reference', sa.String(length=128), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=False),
    sa.Column('short_url', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recovery_attempt_id'], ['recovery_attempts.id'], ),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_payment_requests_provider_reference'), 'recovery_payment_requests', ['provider_reference'], unique=True)
    op.create_index(op.f('ix_recovery_payment_requests_recovery_attempt_id'), 'recovery_payment_requests', ['recovery_attempt_id'], unique=True)
    op.create_index(op.f('ix_recovery_payment_requests_recovery_case_id'), 'recovery_payment_requests', ['recovery_case_id'], unique=False)
    op.create_index(op.f('ix_recovery_payment_requests_reference_id'), 'recovery_payment_requests', ['reference_id'], unique=True)
    op.create_index(op.f('ix_recovery_payment_requests_status'), 'recovery_payment_requests', ['status'], unique=False)
    # batch_alter_table: SQLite can't ALTER a table to add a named unique
    # constraint directly (only Postgres/etc. support that in place) — batch
    # mode transparently does the copy-and-move SQLite needs, and is a
    # plain passthrough (no behavior change) on backends that don't need it.
    with op.batch_alter_table('recovery_attempts') as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('correlation_id', sa.String(length=64), nullable=True))
        batch_op.create_index(
            op.f('ix_recovery_attempts_correlation_id'), ['correlation_id'], unique=False
        )
        batch_op.create_unique_constraint('uq_recovery_attempts_idempotency_key', ['idempotency_key'])
    # server_default on these two: autogenerate doesn't know about the
    # Python-side `default=` on the model, and without one, adding a
    # NOT NULL column to a table that already has rows fails outright
    # (nothing to backfill existing rows with). New rows go through the
    # ORM and get the Python-side default as usual; server_default only
    # matters for rows that already existed before this migration.
    op.add_column(
        'recovery_cases', sa.Column('version', sa.Integer(), nullable=False, server_default='1')
    )
    op.add_column(
        'recovery_cases', sa.Column('recovered_amount', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'recovered_amount')
    op.drop_column('recovery_cases', 'version')
    with op.batch_alter_table('recovery_attempts') as batch_op:
        batch_op.drop_constraint('uq_recovery_attempts_idempotency_key', type_='unique')
        batch_op.drop_index(op.f('ix_recovery_attempts_correlation_id'))
        batch_op.drop_column('correlation_id')
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('currency')
        batch_op.drop_column('provider')
    op.drop_index(op.f('ix_recovery_payment_requests_status'), table_name='recovery_payment_requests')
    op.drop_index(op.f('ix_recovery_payment_requests_reference_id'), table_name='recovery_payment_requests')
    op.drop_index(op.f('ix_recovery_payment_requests_recovery_case_id'), table_name='recovery_payment_requests')
    op.drop_index(op.f('ix_recovery_payment_requests_recovery_attempt_id'), table_name='recovery_payment_requests')
    op.drop_index(op.f('ix_recovery_payment_requests_provider_reference'), table_name='recovery_payment_requests')
    op.drop_table('recovery_payment_requests')
    op.drop_index(op.f('ix_processed_webhook_events_dedup_key'), table_name='processed_webhook_events')
    op.drop_table('processed_webhook_events')
    # ### end Alembic commands ###
